### ISSUE TITLE
Issue for load pilots list

### ISSUE THREAD

**Issue by olivier0253** [UAV-Painkillers/rotorhazard-msp-osd-injector#1]
First of all, thank you for your job§

During the firt tests, i can't display "pilots list" at the end :/
firmware & filesystem are ok. I have tested with 2 rx, but same result..
In settings, i enter the hostname (for the pi, isn't it?), and the port (but i have no nore success).
Can you tell me if I have anything to correct?
Bonus question: on RH, we must be on the current race tab, or does it take the pilot's list created to the event?
Thank you in advance

**Comment by jappyjan** [comment]
Hello,

the pilots are loaded from the general list of pilots that are created, it doesnt matter if they are assigned to any event or not.

the hostname should be set to whatever hostname you use to access the rotorhazard web ui.
for example, if you access rotorhazard with the following address in your browser:
´http://racetimer.local:5000`

then the hostname is `racetimer.local`
the port is `5000`

if you access rotorhazard with a address like this:
`http://192.168.1.23` (no colon ":" and number at the end)

then the hostname is `192.168.1.23`
and the port is `80` (if there is no port in the url, it means it is 80)

if you access rotorhazard with an address that starts with `https://`
then i am sorry, it wont work with this firmware, it means your rotorhazard is using SSL to create a secure connection and sadly the socket library i use to connect to rotorhazard does not support SSL :/ 

i hope this helped you.


PS: sometimes you need to reload the webui after changing/saving the rotorhazard connection details in order to successfully load pilots from rotorhazard, its a known bug but i did not yet find time to fix it

**Comment by olivier0253** [comment]
Hello,

Thank you for your detailled answer.

Hostname is now correctly set. But my raspberry use https to access at setup page :(
I will look at pro/cons about http for my situation (if it's possible)

Good luck for the rest of your work, thank you again!
